INSERT INTO IDEV.THEATER
(THEATER_IDX, THEATER_NAME, THEATER_FEE, SEAT_NUMBER)
VALUES(1, '프레또대극장', 'R석 50,000원 / S석 40,000원 / A석 30,000원', 200);
INSERT INTO IDEV.THEATER
(THEATER_IDX, THEATER_NAME, THEATER_FEE, SEAT_NUMBER)
VALUES(2, '프레또소극장', '전석 30,000원', 200);


INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'A', 20);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'B', 20);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'C', 20);


INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'D', 20);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'E', 20);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 2, '일반', 30000, 'F', 20);

