INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 20);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 21);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 22);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 23);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 24);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'A', 25);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 20);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 21);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 22);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 23);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 24);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'R', 50000, 'B', 25);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 20);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 21);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 22);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 23);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 24);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'C', 25);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 20);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 21);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 22);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 23);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 24);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'S', 40000, 'D', 25);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 20);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 21);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 22);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 23);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 24);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'E', 25);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 20);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 21);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 22);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 23);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 24);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'F', 25);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 20);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 21);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 22);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 23);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 24);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'G', 25);

INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 1);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 2);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 3);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 4);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 5);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 6);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 7);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 8);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 9);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 10);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 11);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 12);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 13);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 14);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 15);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 16);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 17);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 18);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 19);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 20);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 21);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 22);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 23);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 24);
INSERT INTO IDEV.SEAT
(SEAT_IDX, THEATER_IDX, SEAT_GRADE, SEAT_PRICE, SEAT_ROW, NUM)
VALUES(seat_idx_seq.nextval, 1, 'A', 30000, 'H', 25);